# Site settings
title: Documentation Center
email: hello@scalingo.com
description: > # this means to ignore newlines until "baseurl:"
  Scalingo Documentation Center
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://doc.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
highlighter: rouge

permalink: none

defaults:
  - # set default layout on all pages
    scope:
      path: ""
      type: "posts" # in jekyll files outside of _posts are of type pages
    values:
      layout: "page"

gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - Procfile
  - config/puma.rb

array: [] # hack for creating array
