# Site settings
title: Documentation Center
email: hello@scalingo.com
description: > # this means to ignore newlines until "baseurl:"
  Scalingo Documentation Center
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://doc.scalingo.com"
twitter_username: ScalingoHQ
github_username:  Scalingo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
markdown_ext: "md,markdown,mkdown,mkdn,mkd"
highlighter: rouge

permalink: /:categories/:slug

source: src

keep_files:
  - packs

collections:
  tutorials:
    output: true
    permalink: /:collection/:path

  tutorials_categories:
    output: true
    permalink: /tutorials/cat/:name

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: page

  - scope:
      path: ""
      type: pages
    values:
      layout: page

  - scope:
      type: tutorials
    values:
      layout: tutorials_page

  - scope:
      type: tutorials_categories
    values:
      layout: tutorials_category

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

exclude:
  - tmp
  - app/javascript
  - _plugins

highlighted:
  first_steps:
    - /platform/getting-started/first-steps
    - /platform/deployment/deployment-process
    - /platform/getting-started/free-trial
    - /platform/getting-started/how-to-migrate-from-heroku
  popular:
    - /platform/getting-started/troubleshooting-ssh
    - /tools/cli/start
    - /platform/app/log-drain
    - /platform/deployment/deployment-process
    - /platform/getting-started/common-deployment-errors
    - /languages/nodejs/start
    - /languages/php/start
    - /databases/postgresql/about/overview
  technologies:
    - name: Ruby on Rails
      url: /languages/ruby/rails/start
      logo: ruby-on-rails
    - name: NodeJS
      url: "/languages/nodejs/start"
      logo: nodejs
    - name: PHP
      url: "/languages/php/start"
      logo: php
    - name: Python
      url: "/languages/python/start"
      logo: python
    - name: Java
      url: "/languages/java/start"
      logo: java
    - name: MeteorJS
      url: "/languages/meteorjs/start"
      logo: meteorjs

languages:
  - url: go
    name: "Go"
    logo: go
  - url: meteorjs
    name: "MeteorJS"
    logo: meteorjs
  - url: nodejs
    name: "Node.js"
    logo: nodejs
  - url: php
    name: "PHP"
    logo: php
  - url: groovy
    name: "Groovy"
    logo: groovy
  - url: java
    name: "Java"
    logo: java
  - url: clojure
    name: "Clojure"
    logo: clojure
  - url: crystal
    name: "Crystal"
    logo: crystal
  - url: elixir
    name: "Elixir"
    logo: elixir
  - url: python
    name: "Python"
    logo: python
  - url: ruby
    name: "Ruby"
    logo: ruby
  - url: scala
    name: "Scala"
    logo: scala

databases:
  - url: "/databases/postgresql/overview"
    name: "Scalingo for PostgreSQL®"
    logo: postgresql
  - url: "/databases/mysql/overview"
    name: "Scalingo for MySQL®"
    logo: mysql
  - url: "/databases/opensearch/about/overview"
    name: "Scalingo for OpenSearch®"
    logo: opensearch
  - url: "/databases/mongodb/start"
    name: "Scalingo for MongoDB®"
    logo: mongodb
  - url: "/databases/redis/start"
    name: "Scalingo for Caching"
    logo: scalingo-for-caching
  - url: "/databases/influxdb/start"
    name: "Scalingo for InfluxDB®"
    logo: influxdb

samples:
  - url: ruby-rails
    name: Ruby/Rails
    logo: ruby-on-rails
  - url: go-gin
    name: Go/Gin
    logo: go
  - url: nextjs-standalone
    name: Next.js (standalone)
    logo: nextjs
  - url: node-nuxt
    name: NodeJS/Nuxt.js
    logo: nodejs
  - url: php-laravel
    name: PHP/Laravel
    logo: php-laravel
  - url: php-symfony
    name: PHP/Symfony
    logo: php-symfony
  - url: python-django
    name: Python/Django
    logo: python-django
  - url: python-fastapi
    name: Python/FastAPI
    logo: python-fastapi
  - url: elixir-plug
    name: Elixir/Plug
    logo: elixir
  - url: java-spark
    name: Java/Spark
    logo: java-spark

extlinks:
  followed_domains:
    - "scalingo.com"
    - "my.scalingo.com"
    - "dashboard.scalingo.com"
    - "cli.scalingo.com"
    - "blog.scalingo.com"
    - "developers.scalingo.com"
