dependencies = []
description = "Documentation website for Scalingo platform"
destination_server = ["scalingo-platform"]
flags = ["scalingo-app"]
languages = ["dockerfile", "javascript", "markdown", "ruby"]
owner = "jean@scalingo.com"
team = "UFS"
version = "1.0.2"
